//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardCollections.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StandardCollections.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array is not long enough..
        /// </summary>
        internal static string Argument_ArrayNotLongEnought {
            get {
                return ResourceManager.GetString("Argument_ArrayNotLongEnought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to operate on an array with the incorrect number of dimensions..
        /// </summary>
        internal static string Argument_ArrayRank {
            get {
                return ResourceManager.GetString("Argument_ArrayRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target array type is not compatible with the type of items in current context..
        /// </summary>
        internal static string Argument_InvalidArrayType {
            get {
                return ResourceManager.GetString("Argument_InvalidArrayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node is attached to another {0}..
        /// </summary>
        internal static string Argument_LinkedNode_G {
            get {
                return ResourceManager.GetString("Argument_LinkedNode_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for &quot;source&quot; argument, this collection only allows links with a common source..
        /// </summary>
        internal static string Argument_LinkSourceInvalid {
            get {
                return ResourceManager.GetString("Argument_LinkSourceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for &quot;target&quot; argument, this collection only allows links with a common target..
        /// </summary>
        internal static string Argument_LinkTargetInvalid {
            get {
                return ResourceManager.GetString("Argument_LinkTargetInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lowerBound is greater than upperBound.
        /// </summary>
        internal static string Argument_lowerBiggerThanUpper {
            get {
                return ResourceManager.GetString("Argument_lowerBiggerThanUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lower bound of target array must be zero..
        /// </summary>
        internal static string Argument_LowerBoundArrayNotZero {
            get {
                return ResourceManager.GetString("Argument_LowerBoundArrayNotZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dimensions of the specified matrixes are different..
        /// </summary>
        internal static string Argument_MatrixDimensionsNotMatch {
            get {
                return ResourceManager.GetString("Argument_MatrixDimensionsNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified argument is null or does not represents an instance of the {0} class..
        /// </summary>
        internal static string Argument_NullOrNotSpectedType_G {
            get {
                return ResourceManager.GetString("Argument_NullOrNotSpectedType_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified source is do not exist in the collection. Use a contained key as source..
        /// </summary>
        internal static string Argument_SourceMissed {
            get {
                return ResourceManager.GetString("Argument_SourceMissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified target is do not exist in the collection. Use a contained key as target..
        /// </summary>
        internal static string Argument_TargetMissed {
            get {
                return ResourceManager.GetString("Argument_TargetMissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified matrixes do not share the Base value..
        /// </summary>
        internal static string Argument_TriangularBaseNotMatch {
            get {
                return ResourceManager.GetString("Argument_TriangularBaseNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node does not belong to current {0}..
        /// </summary>
        internal static string Argument_UnknownNode_G {
            get {
                return ResourceManager.GetString("Argument_UnknownNode_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not of type &apos;{1}&apos; and cannot be used in this generic context..
        /// </summary>
        internal static string Argument_WrongType_G {
            get {
                return ResourceManager.GetString("Argument_WrongType_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index was out of range. Must be in a valid column range..
        /// </summary>
        internal static string ArgumentOutOfRange_ColIndex {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_ColIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An entry contained in the specified collection is out of the bound of the matrix..
        /// </summary>
        internal static string ArgumentOutOfRange_EntryOutOfBounds {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_EntryOutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index was out of range. Must be non-negative and less than the size of the collection..
        /// </summary>
        internal static string ArgumentOutOfRange_Index {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive value is required..
        /// </summary>
        internal static string ArgumentOutOfRange_Negative {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid values are between &apos;{0}&apos; and &apos;{1}&apos;, inclusive..
        /// </summary>
        internal static string ArgumentOutOfRange_Range_G {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_Range_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index was out of range. Must be in a valid row range..
        /// </summary>
        internal static string ArgumentOutOfRange_RowIndex {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_RowIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indices were out of the modifiable bounds of the matrix. Please try to modify a valid range value..
        /// </summary>
        internal static string ArgumentOutOfRange_TriangularIndex {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_TriangularIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified argument was out of the range of valid values. Specify a value inside the current view bounds..
        /// </summary>
        internal static string ArgumentOutOfRange_ViewValue {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_ViewValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to cast object of type {0} to type {1} which is the return type of the &quot;{2}&quot; operation according to the specified arithmetic operator argument..
        /// </summary>
        internal static string InvalidCast_ReturnTypeNotCompatible_G {
            get {
                return ResourceManager.GetString("InvalidCast_ReturnTypeNotCompatible_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix has been modified. Current column index does not exist anymore..
        /// </summary>
        internal static string InvalidOperation_ColumnIndex {
            get {
                return ResourceManager.GetString("InvalidOperation_ColumnIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current matrix does not allows default values..
        /// </summary>
        internal static string InvalidOperation_DefaultValueNotAllowed {
            get {
                return ResourceManager.GetString("InvalidOperation_DefaultValueNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection is empty..
        /// </summary>
        internal static string InvalidOperation_EmptyCollection {
            get {
                return ResourceManager.GetString("InvalidOperation_EmptyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection was modified; enumeration operation may not excecute..
        /// </summary>
        internal static string InvalidOperation_EnumCorrupt {
            get {
                return ResourceManager.GetString("InvalidOperation_EnumCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration already finished.
        /// </summary>
        internal static string InvalidOperation_EnumEnded {
            get {
                return ResourceManager.GetString("InvalidOperation_EnumEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration has either not started or has already finished.
        /// </summary>
        internal static string InvalidOperation_EnumInvalid {
            get {
                return ResourceManager.GetString("InvalidOperation_EnumInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration has not started. Call MoveNext()..
        /// </summary>
        internal static string InvalidOperation_EnumNotStarted {
            get {
                return ResourceManager.GetString("InvalidOperation_EnumNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph was modified; node key does not exist anymore..
        /// </summary>
        internal static string InvalidOperation_GraphKeyMissed {
            get {
                return ResourceManager.GetString("InvalidOperation_GraphKeyMissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph was modified; source and/or target key does not exist anymore..
        /// </summary>
        internal static string InvalidOperation_GraphKeysRelation {
            get {
                return ResourceManager.GetString("InvalidOperation_GraphKeysRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph was modified; element does not exist anymore..
        /// </summary>
        internal static string InvalidOperation_GraphRelationBroken {
            get {
                return ResourceManager.GetString("InvalidOperation_GraphRelationBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method call is invalid for this collection..
        /// </summary>
        internal static string InvalidOperation_InvMethodCall {
            get {
                return ResourceManager.GetString("InvalidOperation_InvMethodCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underlying collection was modified; current key is not contained anymore..
        /// </summary>
        internal static string InvalidOperation_KeyMissedOnCollection {
            get {
                return ResourceManager.GetString("InvalidOperation_KeyMissedOnCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The left matrix operand should have the same dimensions (row and column) than the second matrix column dimension in order to be modified by this operation..
        /// </summary>
        internal static string InvalidOperation_MatrixDimensionInvalid {
            get {
                return ResourceManager.GetString("InvalidOperation_MatrixDimensionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The matrices should have the same number of Rows and Columns to perform this operation..
        /// </summary>
        internal static string InvalidOperation_MatrixDimensionsNotMatches {
            get {
                return ResourceManager.GetString("InvalidOperation_MatrixDimensionsNotMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix dimensions are too big to perform current operation..
        /// </summary>
        internal static string InvalidOperation_MatrixDimensionsTooBig {
            get {
                return ResourceManager.GetString("InvalidOperation_MatrixDimensionsTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The left matrix operand threw when trying to modify index [{0},{1}]..
        /// </summary>
        internal static string InvalidOperation_MatrixNotAccessible_G {
            get {
                return ResourceManager.GetString("InvalidOperation_MatrixNotAccessible_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first matrix should have the same number of rows than the second matrix number of columns. And also the same number of columns than the second matrix number of rows..
        /// </summary>
        internal static string InvalidOperation_MultiplicityDimensionsNotMatch {
            get {
                return ResourceManager.GetString("InvalidOperation_MultiplicityDimensionsNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current disjoint set has no subset associated. Almost one subset is required to perform this operation..
        /// </summary>
        internal static string InvalidOperation_NoSubsetContained {
            get {
                return ResourceManager.GetString("InvalidOperation_NoSubsetContained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current operation can not be performed over the elements in a sparse matrix.
        /// </summary>
        internal static string InvalidOperation_NotAllowedOnASparseMatrix {
            get {
                return ResourceManager.GetString("InvalidOperation_NotAllowedOnASparseMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix has been modified. Current row index does not exist anymore..
        /// </summary>
        internal static string InvalidOperation_RowIndex {
            get {
                return ResourceManager.GetString("InvalidOperation_RowIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set was modified; sub set does not exist anymore..
        /// </summary>
        internal static string InvalidOperation_SetKeyMissed {
            get {
                return ResourceManager.GetString("InvalidOperation_SetKeyMissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given key was not present in the disjoint set..
        /// </summary>
        internal static string KeyNotFound_DSetInvalidKey {
            get {
                return ResourceManager.GetString("KeyNotFound_DSetInvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection is read-only..
        /// </summary>
        internal static string NotSupported_ReadOnlyCollection {
            get {
                return ResourceManager.GetString("NotSupported_ReadOnlyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The serialized Count information doesn&apos;t match the number of items..
        /// </summary>
        internal static string Serialization_CountNotMatch {
            get {
                return ResourceManager.GetString("Serialization_CountNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnDeserialization method was called while the object was not being deserialized..
        /// </summary>
        internal static string Serialization_InvalidOnDeserialization {
            get {
                return ResourceManager.GetString("Serialization_InvalidOnDeserialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Values for this collection are missing..
        /// </summary>
        internal static string Serialization_ValuesMissing {
            get {
                return ResourceManager.GetString("Serialization_ValuesMissing", resourceCulture);
            }
        }
    }
}
